### ISSUE TITLE
clothesAPI modifyCloth에서 changedList 타입 list로 지정한 부분에서 빌드 에러

### ISSUE THREAD

**Issue by wodnd0131** [MJU-TeamProject2/MJU-FE#86]
clothesAPI modifyCloth에서 changedList 타입 list로 지정한 부분에서 빌드 에러

**Comment by seongje00416** [comment]
@wodnd0131 구체적으로 어떤 시나리오를 수행하는 과정에서 에러가 나는지 전달 부탁드립니다. 해당 에러를 어떻게 하면 재현할 수 있을지 알려주시면 감사하겠습니다.
